{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "sre-rag.labels" . | nindent 4 }}
    {{- include "sre-rag.postgresql.selectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgresql.service.port }}
      targetPort: tcp-postgresql
      protocol: TCP
      name: tcp-postgresql
  selector:
    {{- include "sre-rag.postgresql.selectorLabels" . | nindent 4 }}
{{- end }}
